### ISSUE TITLE
Where should i put the user token? 

### ISSUE THREAD

**Issue by NOTMADDY** [HypnoticSiege/Discord-Buttons-RPC#1]
I can't seem to find a place to put my token pls help

**Comment by HypnoticSiege** [comment]
No token is necessary for this to work. Just the Application ID which you can find on the Discord Developer Portal.
All settings you will need are listed in config.json :)

**Comment by NOTMADDY** [comment]
thanks bud that helped :)

**Comment by HypnoticSiege** [comment]
Of course! 💙
